# Generated by Django 5.1.2 on 2024-10-25 23:19
from django.db import migrations

def add_device_types(apps, schema_editor):
    TipoDispositivo = apps.get_model('devices', 'TipoDispositivo')
    
    tipos = [
        {
            'nombre': 'Luz',
            'descripcion': 'Dispositivo de iluminación controlable'
        },
        {
            'nombre': 'Alarma',
            'descripcion': 'Sistema de alarma y seguridad'
        },
        {
            'nombre': 'Motor',
            'descripcion': 'Motor para puertas, ventanas o persianas'
        }
    ]
    
    for tipo in tipos:
        TipoDispositivo.objects.create(**tipo)

def remove_device_types(apps, schema_editor):
    TipoDispositivo = apps.get_model('devices', 'TipoDispositivo')
    TipoDispositivo.objects.all().delete()

class Migration(migrations.Migration):
    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_device_types, remove_device_types),
    ]