# Generated by Django 5.1.2 on 2024-10-23 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Sistema Habilitado')),
                ('disabled_message', models.CharField(default='El sistema está temporalmente deshabilitado', max_length=255, verbose_name='Mensaje cuando está deshabilitado')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Última modificación')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_modifications', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Estado del Sistema',
                'verbose_name_plural': 'Estado del Sistema',
            },
        ),
    ]
