# Generated by Django 5.1.2 on 2024-10-23 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminpasswordstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstiloCasa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_nacimiento', models.DateField()),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('incluir_pago', models.BooleanField(default=False)),
                ('email_verificado', models.BooleanField(default=False)),
                ('codigo_verificacion', models.CharField(blank=True, max_length=6, null=True)),
                ('estilos_casa', models.ManyToManyField(to='accounts.estilocasa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tipos_transporte', models.ManyToManyField(to='accounts.tipotransporte')),
            ],
        ),
    ]
