# Generated by Django 5.1.2 on 2024-10-23 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_initial_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_enviado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='intentos_verificacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultimo_codigo_enviado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
