# Generated by Django 5.1.2 on 2024-10-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_promocionadministrador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='marca_tarjeta',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_tarjetahabiente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_tarjeta',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='numero_verificador',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
