# Generated by Django 5.1.2 on 2024-10-26 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_perfilusuario_fecha_validez_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAdicional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('usuario_adicional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_adicional_de', to=settings.AUTH_USER_MODEL)),
                ('usuario_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_adicionales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Adicional',
                'verbose_name_plural': 'Usuarios Adicionales',
                'unique_together': {('usuario_principal', 'usuario_adicional')},
            },
        ),
    ]
