# Generated by Django 5.1.2 on 2024-10-26 20:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usuarioadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='saldo_bloqueado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_actualizacion_saldo',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
