# Generated by Django 5.1.2 on 2024-10-26 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_perfilusuario_saldo_perfilusuario_saldo_bloqueado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarjetahabiente', models.CharField(max_length=100)),
                ('numero_tarjeta', models.CharField(max_length=16)),
                ('fecha_validez', models.DateField()),
                ('numero_verificador', models.CharField(max_length=4)),
                ('marca_tarjeta', models.CharField(max_length=20)),
                ('es_principal', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metodos_pago', to='accounts.perfilusuario')),
            ],
            options={
                'ordering': ['-es_principal', '-fecha_creacion'],
            },
        ),
    ]
