# Generated by Django 5.1.2 on 2024-10-26 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_metodopago'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='esta_habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_deshabilitado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='razon_deshabilitado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
