# Generated by Django 5.1.2 on 2024-10-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casa',
            name='amenidades',
        ),
        migrations.DeleteModel(
            name='Amenidad',
        ),
        migrations.AddField(
            model_name='casa',
            name='amenidades',
            field=models.TextField(default='Sin amenidades', help_text='Lista de amenidades separadas por comas'),
        ),
    ]
