# Generated by Django 5.1.2 on 2024-10-25 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_initial_configuracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotocasa',
            name='casa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.casa'),
        ),
        migrations.AlterField(
            model_name='fotocasa',
            name='orden',
            field=models.PositiveIntegerField(),
        ),
    ]
