# Generated by Django 5.1.2 on 2024-10-25 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_casa_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
