# Generated by Django 5.1.2 on 2024-10-26 20:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='es_indefinida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('TEMPORAL', 'Reserva Temporal'), ('CONFIRMADA', 'Reserva Confirmada'), ('CANCELADA', 'Reserva Cancelada')], default='TEMPORAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ConfiguracionTiempoSimulado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_por_mes', models.PositiveIntegerField(default=5)),
                ('minutos_reserva_temporal', models.PositiveIntegerField(default=5)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de Tiempo Simulado',
                'verbose_name_plural': 'Configuraciones de Tiempo Simulado',
            },
        ),
    ]
