# Generated by Django 5.1.2 on 2024-10-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_add_default_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='proximo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('TEMPORAL', 'Temporal'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada')], default='TEMPORAL', max_length=20),
        ),
    ]
