# Generated by Django 5.1.2 on 2024-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_reserva_cuotas_pagadas_reserva_cuotas_totales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='tiempo_restante_minutos',
            field=models.FloatField(default=5.0),
        ),
    ]
