# Generated by Django 5.1.2 on 2024-10-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_reserva_tiempo_restante_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='casa',
            name='estado',
            field=models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADA', 'Ocupada'), ('MANTENIMIENTO', 'En Mantenimiento')], default='DISPONIBLE', max_length=20),
        ),
    ]
