# Generated by Django 5.1.2 on 2024-10-28 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0017_add_fecha_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(default='TEMPORAL', max_length=20),
        ),
    ]
