# Generated by Django 5.1.2 on 2024-10-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_ultimo_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
