# Generated by Django 5.1.2 on 2024-10-29 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_reserva_fecha_ultimo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('TEMPORAL', 'Temporal'), ('CONFIRMADA', 'Confirmada'), ('PAGADA', 'Pagada'), ('NO_PAGADO', 'No Pagado')], default='TEMPORAL', max_length=20),
        ),
    ]
